"""create movies table

Revision ID: 22e9067c0fca
Revises: 
Create Date: 2026-08-16 16:17:36.478084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e9067c0fca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('genre', sa.JSON(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('backdrop', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('cast', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
